version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: golint
      - run: go vet
      - run: go build -v
      - run: go test -v -race ./...
