version: 0.2

#env:
#  variables:
#    KUBE_CLUSTER_NAME: hello.k8s.local

phases:
  install:
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - cd lambda
      - make
      - make bucket
      - make deploy
