AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: kubesnapshot Lambda function

Resources:
  KubeSnapshotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: kubesnapshot
      Runtime: go1.x
      Events:
        Daily:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *)
      # Environment:
      #   Variables:
      #     DRY_RUN: false
      #     KUBE_CLUSTER_NAME: hello.k8s.local
      #     RETAIN_SNAPSHOTS: 5
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeVolumes
                - ec2:DescribeSnapshots
              Resource: "*"
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ec2:CreateSnapshot
              Resource:
                - arn:aws:ec2:*::snapshot/*
                - arn:aws:ec2:*:*:volume/*
      Timeout: 60
