AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: kubesnapshot Lambda function

Parameters:
  KubeClusterName:
    Type: String
  RetainSnapshots:
    Type: String
    Default: ""
  Schedule:
    Type: String
    Default: cron(0 0 * * ? *)

Resources:
  KubeSnapshotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: kubesnapshot
      Runtime: go1.x
      Events:
        Daily:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
      Environment:
        Variables:
          KUBE_CLUSTER_NAME: !Ref KubeClusterName
          RETAIN_SNAPSHOTS: !Ref RetainSnapshots
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeVolumes
                - ec2:DescribeSnapshots
              Resource: "*"
            - Effect: Allow
              Action:
                - ec2:*
              Resource:
                - arn:aws:ec2:*::snapshot/*
                - arn:aws:ec2:*:*:volume/*
      Timeout: 60
